service: c5-mmf2311-i
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  firstfunction:
    handler: index.firsthandler
    events:
      - httpApi:
          path: /mohamed
          method: get

  secondfunction:
    handler: index.secondhandler
    events:
      - httpApi:
          path: /malik
          method: post

plugins:
  - serverless-offline