service: serverless-http-api-project-1-mmf2311
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  api:
    handler: index.handler
    events:
      - httpApi:
          path: /
          method: post

plugins:
  - serverless-offline